name: Build & upload to Firebase App Distribution 

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make credentials
      run: echo "$CREDENTIALS" | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/credential.properties
      env:
        CREDENTIALS: ${{ secrets.CREDENTIALS }}
    - name: build release 
      run: ./gradlew assembleDebug --stacktrace
    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: app/build/outputs/apk/debug/app-debug.apk
    - name: post message to Slack
      if: success()
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: "New app was deployed!!"
        blocks: |
          [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "New app was deployed!! :clap:"
              }
            },
            {
              "type": "divider"
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*${{ github.event.pull_request.title }}*\nPushed by ${{ github.event.pull_request.user.login }}\n\n*URL*\n${{ github.event.pull_request.url }}"
              },
              "accessory": {
                "type": "image",
                "image_url": "${{ github.event.pull_request.user.avatar_url }}",
                "alt_text": "User Icon"
              }
            },
            {
              "type": "actions",
              "elements": [
                {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Join Test"
                  },
                  "url": "${{ secrets.APP_DISTRIBUTION_URL }}"
                }
              ]
            },
            {
              "type": "divider"
            }
          ]
