name: Build & upload to Firebase App Distribution 

on:
  push:
    branches:
      - test/actions

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: post message to Slack
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: "New app was deployed!! :clap:"
        blocks: |
          [
            {
              "type": "divider"
            },
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*test*\nPushed by ${{ github.event.pull_request.user.login }}\n\n${{ github.event.pull_request.html_url }}"
              }
            },
            {
              "type": "divider"
            },
            {
              "type": "actions",
              "elements": [
                {
                  "type": "button",
                  "text": {
                  	"type": "plain_text",
                  	"text": "Join Test",
                  	"emoji": true
                  },
                  "url": "https://console.firebase.google.com/project/notificationwatcher-10eaf/appdistribution/app/android:com.tick.taku.notificationwatcher.debug/releases"
                }
              ]
            }
          ]
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
