name: Build & upload to Firebase App Distribution 

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make credentials
      run: echo "$CREDENTIALS" | base64 --decode --ignore-garbage > $GITHUB_WORKSPACE/credential.properties
      env:
        CREDENTIALS: ${{ secrets.CREDENTIALS }}
    - name: build release 
      run: ./gradlew assembleDebug --stacktrace
    - name: upload artifact to Firebase App Distribution
      if: github.event.pull_request.merged == true
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: app/build/outputs/apk/debug/app-debug.apk
    - name: post message to Slack
      if: success()
      uses: tokorom/action-slack-incoming-webhook@master
      env:
        INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      with:
        text: "New app was deployed!! :clap:"
        blocks: |
        [
          {
            "type": "divider"
          },
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "*test*\nPushed by ${{ github.event.pull_request.user.login }}\n\n${{ github.event.pull_request.html_url }}"
            },
            "accessory": {
              "type": "image",
              "image_url": "${{ github.event.pull_request.user.login }}",
              "alt_text": "User Icon"
            }
          },
          {
            "type": "divider"
          },
          {
            "type": "actions",
            "elements": [
              {
                "type": "button",
                "text": {
                	"type": "plain_text",
                	"text": "Join Test",
                	"emoji": true
                },
                "url": "https://console.firebase.google.com/project/notificationwatcher-10eaf/appdistribution/app/android:com.tick.taku.notificationwatcher.debug/releases"
              }
            ]
          }
        ]
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
